ghost/urls.py
from django.urls import path

from . import views

app_name = 'ghost'
urlpatterns = [
    path('', views.index, name='index'),
    path('ghost_worker', views.ghost_worker, name='ghost_worker'),
    path('db_connection', views.db_connection, name='db_connection')
]

ghostWorkers/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ghost/', include('ghost.urls'))
]

ghost/models.py
from django.db import models

# Create your models here.

ghost/forms.py
from django import forms


class dbDetails(forms.Form):
    database_name = forms.CharField(max_length=50)
    database_user = forms.CharField(max_length=20)
    database_password = forms.CharField(widget=forms.PasswordInput)

ghost/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from .forms import dbDetails
import mysql.connector
from datetime import datetime, timedelta


def index(request):
    context = {}
    context['form'] = dbDetails()
    return render(request, 'ghost/index.html', context)


def db_connection(request):
    if request.method == 'POST':
        dbName = request.POST['database_name']
        dbUser = request.POST['database_user']
        dbPassword = request.POST['database_password']

        mydb = mysql.connector.connect(
            host="localhost",
            user=dbUser,
            password=dbPassword,
            database=dbName
        )

        return ghost_worker(request, mydb)

    return render(request, 'ghost/index.html')


def ghost_worker(request, connection):
    def hashable(val):
        try:
            hash(val)
            return True
        except TypeError:
            return False

    ghost_workers = []
    with connection.cursor() as cursor:
        # ssconstraints = datetime.now() - timedelta(days=365)
        cursor.execute("""
            SELECT employee.employee_id, employee.emp_name, employee.email, employee.department, employee.position,
            worklog.start_time AS start, attendance.attendance_date AS last_attendance_date
            FROM employee
            LEFT JOIN worklog ON employee.employee_id = worklog.employee_id
            LEFT JOIN attendance ON employee.employee_id = attendance.employee_id
            WHERE worklog.start_time IS NULL
        """)

        data = cursor.fetchall()

        for data in data:

            employee = {
                'id': data[0],
                'name': data[1],
                'email': data[2],
                'department': data[3],
                'position': data[4],
            }

            ghost_workers.append(employee)
            ghost_workers_set = set(frozenset((k, str(v)) for k, v in i.items() if hashable(v))
                                    for i in ghost_workers)

            ghost_workers = [dict(j) for j in ghost_workers_set]

    return render(request, 'ghost/ghost_workers.html', {'ghost_workers': ghost_workers})

ghost/templates/ghost/ghost_workers.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css" />
    <title>Ghost Workers</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            background-color: #1f1f1f;
            color: #d9d9d9;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            display: flex;
            margin: o;
            flex-direction: column;
            width: 100%;
            height: 100%;
            align-items: center;
            justify-content: center;
        }
        
        table {
            margin: 2rem auto;
            border-collapse: collapse;
            width: 80%;
        }
        
        th {
            background-color: #292929;
            color: #d9d9d9;
            text-align: left;
            padding: 0.5rem;
        }
        
        th:first-child {
            border-top-left-radius: 5px;
            border-bottom-left-radius: 5px;
        }
        
        th:last-child {
            border-top-right-radius: 5px;
            border-bottom-right-radius: 5px;
        }
        
        td {
            border: 1px solid #292929;
            padding: 0.5rem;
        }
    </style>
</head>

<body class="ghost--list">
    <!-- ghost_workers.html -->
    <h1>Ghost Workers</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Department</th>
                <th>Position</th>
            </tr>
        </thead>
        <tbody>
            {% for ghost_worker in ghost_workers %}
            <tr>
                <td>{{ ghost_worker.id }}</td>
                <td>{{ ghost_worker.name }}</td>
                <td>{{ ghost_worker.email }}</td>
                <td>{{ ghost_worker.department }}</td>
                <td>{{ ghost_worker.position }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">No ghost workers found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

</html>

ghost/templates/ghost/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            background-color: #1f1f1f;
            color: #d9d9d9;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            display: flex;
            margin: o;
            flex-direction: column;
            width: 100%;
            height: 100%;
            align-items: center;
            justify-content: center;
        }
        
        form {
            display: block;
            width: 325px;
            height: 80vh;
            padding: 10px;
        }
        
        fieldset {
            display: block;
            border-radius: 6px;
            padding: 25px;
            background: transparent;
        }
        
        legend {
            font-size: 1.2rem;
            margin-bottom: 1rem;
        }
        
        label {
            font-size: 1.2rem;
            margin-bottom: 1rem;
        }
        
        input[type='text'],
        input[type='password'] {
            padding: 0.5rem;
            border: none;
            border-radius: 5px;
            margin-bottom: 1rem;
            background-color: #292929;
            color: #d9d9d9;
        }
        
        input[type='submit'] {
            padding: 0.5rem;
            border: none;
            border-radius: 5px;
            background-color: #292929;
            color: #d9d9d9;
            cursor: pointer;
            transition: background-color 0.3s ease-in-out;
            margin: 10px;
        }
        
        input[type='submit']:hover {
            background-color: #ffffff;
            color: #292929;
        }
        
        .loader {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            width: 100%;
            height: 100%;
            align-items: center;
            padding-top: 10%;
        }
        
        .loader--spin {
            border: 16px solid #f3f3f3;
            border-top: 16px solid #3498db;
            border-radius: 50%;
            width: 120px;
            height: 120px;
            animation: spin 2s linear infinite;
            margin: auto;
        }
        
        .loader p,
        .loader h1 {
            margin-top: 5%;
            margin-bottom: 5%;
            text-align: center;
            font-weight: bolder;
            font-size: 1.2rem;
        }
        
        @keyframes spin {
            0% {
                transform: rotate(0deg);
            }
            100% {
                transform: rotate(360deg);
            }
        }
    </style>
    <title>Ghost Workers</title>
</head>

<body>
    <div class="loader">
        <h1>Ghost Workers Detector</h1>
        <div class="loader--spin"></div>
        <p>Welcome...</p>
    </div>
    <form action="{% url 'ghost:db_connection'%}" method="post" class="form">
        {% csrf_token %}
        <fieldset>
            <legend>Database</legend>
            {{form }}
            <input type="submit" value="Connect" />
        </fieldset>
    </form>
    <script>
        let loader = document.querySelector('.loader');
        let content = document.querySelector('.form');

        content.style.display = 'none';
        loader.style.display = 'block';

        setTimeout(function() {
            loader.style.display = 'none';

            content.style.display = 'block';
        }, 3000);
    </script>
</body>

</html>